In [2]:
import requests
from datetime import datetime, timedelta
import matplotlib.patches as mpatches
import random
import pickle
import json
import os
import time
from time import sleep
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, ForeignKey

In [3]:
def get_all_episodes():
    total_data = []
    page = 1
    while True:
        response = requests.get(f"https://rickandmortyapi.com/api/episode/?page={page}")
        json_data = response.json()
        total_data.extend(json_data["results"])
        if not json_data["info"]["next"]:
            break
        page += 1
    return total_data

def get_all_locations():
    total_data = []
    page = 1
    while True:
        response = requests.get(f"https://rickandmortyapi.com/api/location/?page={page}")
        if response.status_code == 429:
            print(f"Rate limit en página {page}, esperando...")
            time.sleep(2)
            continue
        if response.status_code != 200:
            print(f"Error en página {page}: status {response.status_code}")
            break
        json_data = response.json()
        total_data.extend(json_data["results"])
        if not json_data["info"]["next"]:
            break
        page += 1
        time.sleep(0.3)
    return total_data

def get_all_characters():
    total_data = []
    page = 1
    while True:
        response = requests.get(f"https://rickandmortyapi.com/api/character/?page={page}")
        if response.status_code == 429:
            print(f"Rate limit en página {page}, esperando...")
            time.sleep(2)
            continue  # reintenta la misma página
        if response.status_code != 200:
            print(f"Error en página {page}: status {response.status_code}")
            break
        json_data = response.json()
        total_data.extend(json_data["results"])
        if not json_data["info"]["next"]:
            break
        page += 1
        time.sleep(0.3)  # pausa entre páginas
    return total_data

In [4]:
data_character = get_all_characters()
data_location = get_all_locations()
data_episodies = get_all_episodes()

In [5]:
data_episodies

[{'id': 1,
  'name': 'Pilot',
  'air_date': 'December 2, 2013',
  'episode': 'S01E01',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/35',
   'https://rickandmortyapi.com/api/character/38',
   'https://rickandmortyapi.com/api/character/62',
   'https://rickandmortyapi.com/api/character/92',
   'https://rickandmortyapi.com/api/character/127',
   'https://rickandmortyapi.com/api/character/144',
   'https://rickandmortyapi.com/api/character/158',
   'https://rickandmortyapi.com/api/character/175',
   'https://rickandmortyapi.com/api/character/179',
   'https://rickandmortyapi.com/api/character/181',
   'https://rickandmortyapi.com/api/character/239',
   'https://rickandmortyapi.com/api/character/249',
   'https://rickandmortyapi.com/api/character/271',
   'https://rickandmortyapi.com/api/character/338',
   'https://rickandmortyapi.com/api/character/394',
   'https://rickandmortyapi.com/api/character/395',
   'https://rickandmortyapi.com/api/character/435'],
  'url': 'https://rickandmortyapi.com/api/episode/1',
  'created': '2017-11-10T12:56:33.798Z'},
 {'id': 2,
  'name': 'Lawnmower Dog',
  'air_date': 'December 9, 2013',
  'episode': 'S01E02',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/38',
   'https://rickandmortyapi.com/api/character/46',
   'https://rickandmortyapi.com/api/character/63',
   'https://rickandmortyapi.com/api/character/80',
   'https://rickandmortyapi.com/api/character/175',
   'https://rickandmortyapi.com/api/character/221',
   'https://rickandmortyapi.com/api/character/239',
   'https://rickandmortyapi.com/api/character/246',
   'https://rickandmortyapi.com/api/character/304',
   'https://rickandmortyapi.com/api/character/305',
   'https://rickandmortyapi.com/api/character/306',
   'https://rickandmortyapi.com/api/character/329',
   'https://rickandmortyapi.com/api/character/338',
   'https://rickandmortyapi.com/api/character/396',
   'https://rickandmortyapi.com/api/character/397',
   'https://rickandmortyapi.com/api/character/398',
   'https://rickandmortyapi.com/api/character/405'],
  'url': 'https://rickandmortyapi.com/api/episode/2',
  'created': '2017-11-10T12:56:33.916Z'},
 {'id': 3,
  'name': 'Anatomy Park',
  'air_date': 'December 16, 2013',
  'episode': 'S01E03',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/12',
   'https://rickandmortyapi.com/api/character/17',
   'https://rickandmortyapi.com/api/character/38',
   'https://rickandmortyapi.com/api/character/45',
   'https://rickandmortyapi.com/api/character/96',
   'https://rickandmortyapi.com/api/character/97',
   'https://rickandmortyapi.com/api/character/98',
   'https://rickandmortyapi.com/api/character/99',
   'https://rickandmortyapi.com/api/character/100',
   'https://rickandmortyapi.com/api/character/101',
   'https://rickandmortyapi.com/api/character/108',
   'https://rickandmortyapi.com/api/character/112',
   'https://rickandmortyapi.com/api/character/114',
   'https://rickandmortyapi.com/api/character/169',
   'https://rickandmortyapi.com/api/character/175',
   'https://rickandmortyapi.com/api/character/186',
   'https://rickandmortyapi.com/api/character/201',
   'https://rickandmortyapi.com/api/character/268',
   'https://rickandmortyapi.com/api/character/300',
   'https://rickandmortyapi.com/api/character/302',
   'https://rickandmortyapi.com/api/character/338',
   'https://rickandmortyapi.com/api/character/356'],
  'url': 'https://rickandmortyapi.com/api/episode/3',
  'created': '2017-11-10T12:56:34.022Z'},
 {'id': 4,
  'name': 'M. Night Shaym-Aliens!',
  'air_date': 'January 13, 2014',
  'episode': 'S01E04',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/38',
   'https://rickandmortyapi.com/api/character/87',
   'https://rickandmortyapi.com/api/character/175',
   'https://rickandmortyapi.com/api/character/179',
   'https://rickandmortyapi.com/api/character/181',
   'https://rickandmortyapi.com/api/character/191',
   'https://rickandmortyapi.com/api/character/239',
   'https://rickandmortyapi.com/api/character/241',
   'https://rickandmortyapi.com/api/character/270',
   'https://rickandmortyapi.com/api/character/337',
   'https://rickandmortyapi.com/api/character/338'],
  'url': 'https://rickandmortyapi.com/api/episode/4',
  'created': '2017-11-10T12:56:34.129Z'},
 {'id': 5,
  'name': 'Meeseeks and Destroy',
  'air_date': 'January 20, 2014',
  'episode': 'S01E05',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/38',
   'https://rickandmortyapi.com/api/character/41',
   'https://rickandmortyapi.com/api/character/89',
   'https://rickandmortyapi.com/api/character/116',
   'https://rickandmortyapi.com/api/character/117',
   'https://rickandmortyapi.com/api/character/120',
   'https://rickandmortyapi.com/api/character/175',
   'https://rickandmortyapi.com/api/character/193',
   'https://rickandmortyapi.com/api/character/238',
   'https://rickandmortyapi.com/api/character/242',
   'https://rickandmortyapi.com/api/character/271',
   'https://rickandmortyapi.com/api/character/303',
   'https://rickandmortyapi.com/api/character/326',
   'https://rickandmortyapi.com/api/character/333',
   'https://rickandmortyapi.com/api/character/338',
   'https://rickandmortyapi.com/api/character/343',
   'https://rickandmortyapi.com/api/character/399',
   'https://rickandmortyapi.com/api/character/400'],
  'url': 'https://rickandmortyapi.com/api/episode/5',
  'created': '2017-11-10T12:56:34.236Z'},
 {'id': 6,
  'name': 'Rick Potion #9',
  'air_date': 'January 27, 2014',
  'episode': 'S01E06',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/3',
   'https://rickandmortyapi.com/api/character/4',
   'https://rickandmortyapi.com/api/character/5',
   'https://rickandmortyapi.com/api/character/38',
   'https://rickandmortyapi.com/api/character/58',
   'https://rickandmortyapi.com/api/character/82',
   'https://rickandmortyapi.com/api/character/83',
   'https://rickandmortyapi.com/api/character/92',
   'https://rickandmortyapi.com/api/character/155',
   'https://rickandmortyapi.com/api/character/175',
   'https://rickandmortyapi.com/api/character/179',
   'https://rickandmortyapi.com/api/character/181',
   'https://rickandmortyapi.com/api/character/216',
   'https://rickandmortyapi.com/api/character/234',
   'https://rickandmortyapi.com/api/character/239',
   'https://rickandmortyapi.com/api/character/249',
   'https://rickandmortyapi.com/api/character/251',
   'https://rickandmortyapi.com/api/character/271',
   'https://rickandmortyapi.com/api/character/293',
   'https://rickandmortyapi.com/api/character/338',
   'https://rickandmortyapi.com/api/character/343',
   'https://rickandmortyapi.com/api/character/394'],
  'url': 'https://rickandmortyapi.com/api/episode/6',
  'created': '2017-11-10T12:56:34.339Z'},
 {'id': 7,
  'name': 'Raising Gazorpazorp',
  'air_date': 'March 10, 2014',
  'episode': 'S01E07',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/3',
   'https://rickandmortyapi.com/api/character/4',
   'https://rickandmortyapi.com/api/character/5',
   'https://rickandmortyapi.com/api/character/59',
   'https://rickandmortyapi.com/api/character/151',
   'https://rickandmortyapi.com/api/character/168',
   'https://rickandmortyapi.com/api/character/211',
   'https://rickandmortyapi.com/api/character/230',
   'https://rickandmortyapi.com/api/character/258',
   'https://rickandmortyapi.com/api/character/329',
   'https://rickandmortyapi.com/api/character/376',
   'https://rickandmortyapi.com/api/character/401'],
  'url': 'https://rickandmortyapi.com/api/episode/7',
  'created': '2017-11-10T12:56:34.441Z'},
 {'id': 8,
  'name': 'Rixty Minutes',
  'air_date': 'March 17, 2014',
  'episode': 'S01E08',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/3',
   'https://rickandmortyapi.com/api/character/4',
   'https://rickandmortyapi.com/api/character/5',
   'https://rickandmortyapi.com/api/character/20',
   'https://rickandmortyapi.com/api/character/28',
   'https://rickandmortyapi.com/api/character/29',
   'https://rickandmortyapi.com/api/character/34',
   'https://rickandmortyapi.com/api/character/37',
   'https://rickandmortyapi.com/api/character/54',
   'https://rickandmortyapi.com/api/character/88',
   'https://rickandmortyapi.com/api/character/91',
   'https://rickandmortyapi.com/api/character/129',
   'https://rickandmortyapi.com/api/character/134',
   'https://rickandmortyapi.com/api/character/136',
   'https://rickandmortyapi.com/api/character/145',
   'https://rickandmortyapi.com/api/character/153',
   'https://rickandmortyapi.com/api/character/157',
   'https://rickandmortyapi.com/api/character/176',
   'https://rickandmortyapi.com/api/character/183',
   'https://rickandmortyapi.com/api/character/184',
   'https://rickandmortyapi.com/api/character/195',
   'https://rickandmortyapi.com/api/character/207',
   'https://rickandmortyapi.com/api/character/214',
   'https://rickandmortyapi.com/api/character/222',
   'https://rickandmortyapi.com/api/character/250',
   'https://rickandmortyapi.com/api/character/266',
   'https://rickandmortyapi.com/api/character/277',
   'https://rickandmortyapi.com/api/character/279',
   'https://rickandmortyapi.com/api/character/314',
   'https://rickandmortyapi.com/api/character/315',
   'https://rickandmortyapi.com/api/character/316',
   'https://rickandmortyapi.com/api/character/317',
   'https://rickandmortyapi.com/api/character/318',
   'https://rickandmortyapi.com/api/character/351',
   'https://rickandmortyapi.com/api/character/358',
   'https://rickandmortyapi.com/api/character/367',
   'https://rickandmortyapi.com/api/character/370',
   'https://rickandmortyapi.com/api/character/373',
   'https://rickandmortyapi.com/api/character/402',
   'https://rickandmortyapi.com/api/character/403',
   'https://rickandmortyapi.com/api/character/404',
   'https://rickandmortyapi.com/api/character/405',
   'https://rickandmortyapi.com/api/character/406',
   'https://rickandmortyapi.com/api/character/407',
   'https://rickandmortyapi.com/api/character/408',
   'https://rickandmortyapi.com/api/character/409',
   'https://rickandmortyapi.com/api/character/410',
   'https://rickandmortyapi.com/api/character/411',
   'https://rickandmortyapi.com/api/character/412',
   'https://rickandmortyapi.com/api/character/413',
   'https://rickandmortyapi.com/api/character/414',
   'https://rickandmortyapi.com/api/character/415',
   'https://rickandmortyapi.com/api/character/416',
   'https://rickandmortyapi.com/api/character/417',
   'https://rickandmortyapi.com/api/character/418'],
  'url': 'https://rickandmortyapi.com/api/episode/8',
  'created': '2017-11-10T12:56:34.543Z'},
 {'id': 9,
  'name': 'Something Ricked This Way Comes',
  'air_date': 'March 24, 2014',
  'episode': 'S01E09',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/3',
   'https://rickandmortyapi.com/api/character/4',
   'https://rickandmortyapi.com/api/character/5',
   'https://rickandmortyapi.com/api/character/88',
   'https://rickandmortyapi.com/api/character/192',
   'https://rickandmortyapi.com/api/character/240',
   'https://rickandmortyapi.com/api/character/243',
   'https://rickandmortyapi.com/api/character/251',
   'https://rickandmortyapi.com/api/character/272',
   'https://rickandmortyapi.com/api/character/307',
   'https://rickandmortyapi.com/api/character/419',
   'https://rickandmortyapi.com/api/character/420',
   'https://rickandmortyapi.com/api/character/421',
   'https://rickandmortyapi.com/api/character/422',
   'https://rickandmortyapi.com/api/character/826'],
  'url': 'https://rickandmortyapi.com/api/episode/9',
  'created': '2017-11-10T12:56:34.645Z'},
 {'id': 10,
  'name': 'Close Rick-counters of the Rick Kind',
  'air_date': 'April 7, 2014',
  'episode': 'S01E10',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/3',
   'https://rickandmortyapi.com/api/character/4',
   'https://rickandmortyapi.com/api/character/5',
   'https://rickandmortyapi.com/api/character/7',
   'https://rickandmortyapi.com/api/character/14',
   'https://rickandmortyapi.com/api/character/15',
   'https://rickandmortyapi.com/api/character/18',
   'https://rickandmortyapi.com/api/character/19',
   'https://rickandmortyapi.com/api/character/21',
   'https://rickandmortyapi.com/api/character/22',
   'https://rickandmortyapi.com/api/character/27',
   'https://rickandmortyapi.com/api/character/39',
   'https://rickandmortyapi.com/api/character/53',
   'https://rickandmortyapi.com/api/character/77',
   'https://rickandmortyapi.com/api/character/78',
   'https://rickandmortyapi.com/api/character/79',
   'https://rickandmortyapi.com/api/character/82',
   'https://rickandmortyapi.com/api/character/83',
   'https://rickandmortyapi.com/api/character/84',
   'https://rickandmortyapi.com/api/character/85',
   'https://rickandmortyapi.com/api/character/86',
   'https://rickandmortyapi.com/api/character/103',
   'https://rickandmortyapi.com/api/character/113',
   'https://rickandmortyapi.com/api/character/118',
   'https://rickandmortyapi.com/api/character/119',
   'https://rickandmortyapi.com/api/character/152',
   'https://rickandmortyapi.com/api/character/164',
   'https://rickandmortyapi.com/api/character/177',
   'https://rickandmortyapi.com/api/character/209',
   'https://rickandmortyapi.com/api/character/215',
   'https://rickandmortyapi.com/api/character/232',
   'https://rickandmortyapi.com/api/character/242',
   'https://rickandmortyapi.com/api/character/274',
   'https://rickandmortyapi.com/api/character/290',
   'https://rickandmortyapi.com/api/character/294',
   'https://rickandmortyapi.com/api/character/295',
   'https://rickandmortyapi.com/api/character/298',
   'https://rickandmortyapi.com/api/character/299',
   'https://rickandmortyapi.com/api/character/329',
   'https://rickandmortyapi.com/api/character/330',
   'https://rickandmortyapi.com/api/character/339',
   'https://rickandmortyapi.com/api/character/349',
   'https://rickandmortyapi.com/api/character/359',
   'https://rickandmortyapi.com/api/character/381',
   'https://rickandmortyapi.com/api/character/389',
   'https://rickandmortyapi.com/api/character/405',
   'https://rickandmortyapi.com/api/character/424',
   'https://rickandmortyapi.com/api/character/425',
   'https://rickandmortyapi.com/api/character/426',
   'https://rickandmortyapi.com/api/character/427',
   'https://rickandmortyapi.com/api/character/428',
   'https://rickandmortyapi.com/api/character/429',
   'https://rickandmortyapi.com/api/character/430',
   'https://rickandmortyapi.com/api/character/431',
   'https://rickandmortyapi.com/api/character/432',
   'https://rickandmortyapi.com/api/character/433',
   'https://rickandmortyapi.com/api/character/434',
   'https://rickandmortyapi.com/api/character/663'],
  'url': 'https://rickandmortyapi.com/api/episode/10',
  'created': '2017-11-10T12:56:34.747Z'},
 {'id': 11,
  'name': 'Ricksy Business',
  'air_date': 'April 14, 2014',
  'episode': 'S01E11',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/3',
   'https://rickandmortyapi.com/api/character/4',
   'https://rickandmortyapi.com/api/character/5',
   'https://rickandmortyapi.com/api/character/7',
   'https://rickandmortyapi.com/api/character/35',
   'https://rickandmortyapi.com/api/character/47',
   'https://rickandmortyapi.com/api/character/58',
   'https://rickandmortyapi.com/api/character/88',
   'https://rickandmortyapi.com/api/character/180',
   'https://rickandmortyapi.com/api/character/181',
   'https://rickandmortyapi.com/api/character/210',
   'https://rickandmortyapi.com/api/character/216',
   'https://rickandmortyapi.com/api/character/251',
   'https://rickandmortyapi.com/api/character/282',
   'https://rickandmortyapi.com/api/character/295',
   'https://rickandmortyapi.com/api/character/308',
   'https://rickandmortyapi.com/api/character/326',
   'https://rickandmortyapi.com/api/character/327',
   'https://rickandmortyapi.com/api/character/331',
   'https://rickandmortyapi.com/api/character/333',
   'https://rickandmortyapi.com/api/character/344',
   'https://rickandmortyapi.com/api/character/362',
   'https://rickandmortyapi.com/api/character/389',
   'https://rickandmortyapi.com/api/character/395',
   'https://rickandmortyapi.com/api/character/405',
   'https://rickandmortyapi.com/api/character/423',
   'https://rickandmortyapi.com/api/character/435',
   'https://rickandmortyapi.com/api/character/436'],
  'url': 'https://rickandmortyapi.com/api/episode/11',
  'created': '2017-11-10T12:56:34.850Z'},
 {'id': 12,
  'name': 'A Rickle in Time',
  'air_date': 'July 26, 2015',
  'episode': 'S02E01',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/3',
   'https://rickandmortyapi.com/api/character/4',
   'https://rickandmortyapi.com/api/character/5',
   'https://rickandmortyapi.com/api/character/11',
   'https://rickandmortyapi.com/api/character/64',
   'https://rickandmortyapi.com/api/character/237',
   'https://rickandmortyapi.com/api/character/313',
   'https://rickandmortyapi.com/api/character/437',
   'https://rickandmortyapi.com/api/character/438',
   'https://rickandmortyapi.com/api/character/439',
   'https://rickandmortyapi.com/api/character/440'],
  'url': 'https://rickandmortyapi.com/api/episode/12',
  'created': '2017-11-10T12:56:34.953Z'},
 {'id': 13,
  'name': 'Mortynight Run',
  'air_date': 'August 2, 2015',
  'episode': 'S02E02',
  'characters': ['https://rickandmortyapi.com/api/character/1',
   'https://rickandmortyapi.com/api/character/2',
   'https://rickandmortyapi.com/api/character/5',
   'https://rickandmortyapi.com/api/character/23',
   'https://rickandmortyapi.com/api/character/28',
   'https://rickandmortyapi.com/api/character/34',
   'https://rickandmortyapi.com/api/character/106',
   'https://rickandmortyapi.com/api/character/122',
   'https://rickandmortyapi.com/api/character/129',
   'https://rickandmortyapi.com/api/character/131',
   'https://rickandmortyapi.com/api/character/133',
   'https://rickandmortyapi.com/api/character/136',
   'https://rickandmortyapi.com/api/character/174',
   'https://rickandmortyapi.com/api/character/180',
   'https://rickandmortyapi.com/api/character/196',
   'https://rickandmortyapi.com/api/character/207',
   'https://rickandmortyapi.com/api/character/242',
   'https://rickandmortyapi.com/api/character/257',
   'https://rickandmortyapi.com/api/character/282',
   'https://rickandmortyapi.com/api/character/309',
   'https://rickandmortyapi.com/api/character/311',
   'https://rickandmortyapi.com/api/character/362',
   'https://rickandmortyapi.com/api/character/386',
   'https://rickandmortyapi.com/api/character/393',
   'https://rickandmortyapi.com/api/character/436',
   'https://rickandmortyapi.com/api/character/441',
   'https://rickandmortyapi.com/api/character/442',

In [6]:
df_episode = pd.DataFrame(data_episodies)
df_episode

,id,name,air_date,episode,characters,url,created
0,1,Pilot,"December 2, 2013",S01E01,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/1,2017-11-10T12:56:33.798Z
1,2,Lawnmower Dog,"December 9, 2013",S01E02,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/2,2017-11-10T12:56:33.916Z
2,3,Anatomy Park,"December 16, 2013",S01E03,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/3,2017-11-10T12:56:34.022Z
3,4,M. Night Shaym-Aliens!,"January 13, 2014",S01E04,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/4,2017-11-10T12:56:34.129Z
4,5,Meeseeks and Destroy,"January 20, 2014",S01E05,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/5,2017-11-10T12:56:34.236Z
5,6,Rick Potion #9,"January 27, 2014",S01E06,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/6,2017-11-10T12:56:34.339Z
6,7,Raising Gazorpazorp,"March 10, 2014",S01E07,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/7,2017-11-10T12:56:34.441Z
7,8,Rixty Minutes,"March 17, 2014",S01E08,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/8,2017-11-10T12:56:34.543Z
8,9,Something Ricked This Way Comes,"March 24, 2014",S01E09,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/9,2017-11-10T12:56:34.645Z
9,10,Close Rick-counters of the Rick Kind,"April 7, 2014",S01E10,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/10,2017-11-10T12:56:34.747Z
10,11,Ricksy Business,"April 14, 2014",S01E11,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/11,2017-11-10T12:56:34.850Z
11,12,A Rickle in Time,"July 26, 2015",S02E01,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/12,2017-11-10T12:56:34.953Z
12,13,Mortynight Run,"August 2, 2015",S02E02,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/13,2017-11-10T12:56:35.055Z
13,14,Auto Erotic Assimilation,"August 9, 2015",S02E03,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/14,2017-11-10T12:56:35.158Z
14,15,Total Rickall,"August 16, 2015",S02E04,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/15,2017-11-10T12:56:35.261Z
15,16,Get Schwifty,"August 23, 2015",S02E05,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/16,2017-11-10T12:56:35.364Z
16,17,The Ricks Must Be Crazy,"August 30, 2015",S02E06,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/17,2017-11-10T12:56:35.467Z
17,18,Big Trouble in Little Sanchez,"September 13, 2015",S02E07,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/18,2017-11-10T12:56:35.569Z
18,19,Interdimensional Cable 2: Tempting Fate,"September 20, 2015",S02E08,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/19,2017-11-10T12:56:35.669Z
19,20,Look Who's Purging Now,"September 27, 2015",S02E09,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/20,2017-11-10T12:56:35.772Z
20,21,The Wedding Squanchers,"October 4, 2015",S02E10,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/21,2017-11-10T12:56:35.875Z
21,22,The Rickshank Rickdemption,"April 1, 2017",S03E01,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/22,2017-11-10T12:56:35.983Z
22,23,Rickmancing the Stone,"July 30, 2017",S03E02,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/23,2017-11-10T12:56:36.100Z
23,24,Pickle Rick,"August 6, 2017",S03E03,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/24,2017-11-10T12:56:36.206Z
24,25,Vindicators 3: The Return of Worldender,"August 13, 2017",S03E04,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/25,2017-11-10T12:56:36.310Z
25,26,The Whirly Dirly Conspiracy,"August 20, 2017",S03E05,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/26,2017-11-10T12:56:36.413Z
26,27,Rest and Ricklaxation,"August 27, 2017",S03E06,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/27,2017-11-10T12:56:36.515Z
27,28,The Ricklantis Mixup,"September 10, 2017",S03E07,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/28,2017-11-10T12:56:36.618Z
28,29,Morty's Mind Blowers,"September 17, 2017",S03E08,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/29,2017-11-10T12:56:36.726Z
29,30,The ABC's of Beth,"September 24, 2017",S03E09,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/30,2017-11-10T12:56:36.828Z
30,31,The Rickchurian Mortydate,"October 1, 2017",S03E10,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/31,2017-11-10T12:56:36.929Z
31,32,"Edge of Tomorty: Rick, Die, Rickpeat","November 10, 2019",S04E01,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/32,2020-04-30T06:52:04.495Z
32,33,The Old Man and the Seat,"November 17, 2019",S04E02,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/33,2020-04-30T06:52:04.498Z
33,34,One Crew Over the Crewcoo's Morty,"November 24, 2019",S04E03,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/34,2020-04-30T06:52:04.498Z
34,35,Claw and Hoarder: Special Ricktim's Morty,"December 8, 2019",S04E04,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/35,2020-04-30T06:52:04.498Z
35,36,Rattlestar Ricklactica,"December 15, 2019",S04E05,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/36,2020-04-30T06:52:04.499Z
36,37,Never Ricking Morty,"May 3, 2020",S04E06,[https://rickandmortyapi.com/api/character/593...,https://rickandmortyapi.com/api/episode/37,2020-08-06T05:44:21.422Z
37,38,Promortyus,"May 10, 2020",S04E07,[https://rickandmortyapi.com/api/character/640...,https://rickandmortyapi.com/api/episode/38,2020-08-06T05:49:40.563Z
38,39,The Vat of Acid Episode,"May 17, 2020",S04E08,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/39,2020-08-06T05:51:07.419Z
39,40,Childrick of Mort,"May 24, 2020",S04E09,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/40,2020-08-06T05:51:25.458Z
40,41,Star Mort: Rickturn of the Jerri,"May 31, 2020",S04E10,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/41,2020-08-06T05:51:52.079Z
41,42,Mort Dinner Rick Andre,"June 20, 2021",S05E01,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/42,2021-10-15T17:00:24.099Z
42,43,Mortyplicity,"June 27, 2021",S05E02,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/43,2021-10-15T17:00:24.102Z
43,44,A Rickconvenient Mort,"July 4, 2021",S05E03,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/44,2021-10-15T17:00:24.102Z
44,45,Rickdependence Spray,"July 11, 2021",S05E04,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/45,2021-10-15T17:00:24.103Z
45,46,Amortycan Grickfitti,"July 18, 2021",S05E05,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/46,2021-10-15T17:00:24.103Z
46,47,Rick & Morty's Thanksploitation Spectacular,"July 25, 2021",S05E06,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/47,2021-10-15T17:00:24.104Z
47,48,Gotron Jerrysis Rickvangelion,"August 1, 2021",S05E07,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/48,2021-10-15T17:00:24.104Z
48,49,Rickternal Friendshine of the Spotless Mort,"August 8, 2021",S05E08,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/49,2021-10-15T17:00:24.104Z
49,50,Forgetting Sarick Mortshall,"September 5, 2021",S05E09,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/50,2021-10-15T17:00:24.105Z
50,51,Rickmurai Jack,"September 5, 2021",S05E10,"[https://rickandmortyapi.com/api/character/1, ...",https://rickandmortyapi.com/api/episode/51,2021-10-15T17:00:24.105Z

In [7]:
df_location = pd.DataFrame(data_location)
df_location

,id,name,type,dimension,residents,url,created
0,1,Earth (C-137),Planet,Dimension C-137,"[https://rickandmortyapi.com/api/character/38,...",https://rickandmortyapi.com/api/location/1,2017-11-10T12:42:04.162Z
1,2,Abadango,Cluster,unknown,[https://rickandmortyapi.com/api/character/6],https://rickandmortyapi.com/api/location/2,2017-11-10T13:06:38.182Z
2,3,Citadel of Ricks,Space station,unknown,"[https://rickandmortyapi.com/api/character/8, ...",https://rickandmortyapi.com/api/location/3,2017-11-10T13:08:13.191Z
3,4,Worldender's lair,Planet,unknown,"[https://rickandmortyapi.com/api/character/10,...",https://rickandmortyapi.com/api/location/4,2017-11-10T13:08:20.569Z
4,5,Anatomy Park,Microverse,Dimension C-137,"[https://rickandmortyapi.com/api/character/12,...",https://rickandmortyapi.com/api/location/5,2017-11-10T13:08:46.060Z
...,...,...,...,...,...,...,...
121,122,Avian Planet,Planet,Replacement Dimension,[https://rickandmortyapi.com/api/character/792...,https://rickandmortyapi.com/api/location/122,2021-10-26T12:19:52.957Z
122,123,Normal Size Bug Dimension,Dimension,,[https://rickandmortyapi.com/api/character/795...,https://rickandmortyapi.com/api/location/123,2021-11-02T13:03:21.307Z
123,124,Slartivart,Planet,Replacement Dimension,[https://rickandmortyapi.com/api/character/797],https://rickandmortyapi.com/api/location/124,2021-11-02T13:07:27.619Z
124,125,Rick and Two Crows Planet,Planet,Replacement Dimension,[https://rickandmortyapi.com/api/character/809...,https://rickandmortyapi.com/api/location/125,2021-11-02T13:50:55.588Z
125,126,Rick's Memories,Memory,,[https://rickandmortyapi.com/api/character/815...,https://rickandmortyapi.com/api/location/126,2021-11-02T15:18:57.987Z

In [8]:
df_character = pd.DataFrame(data_character)
df_character

,id,name,status,species,type,gender,origin,location,image,episode,url,created
0,1,Rick Sanchez,Alive,Human,,Male,"{'name': 'Earth (C-137)', 'url': 'https://rick...","{'name': 'Citadel of Ricks', 'url': 'https://r...",https://rickandmortyapi.com/api/character/avat...,"[https://rickandmortyapi.com/api/episode/1, ht...",https://rickandmortyapi.com/api/character/1,2017-11-04T18:48:46.250Z
1,2,Morty Smith,Alive,Human,,Male,"{'name': 'unknown', 'url': ''}","{'name': 'Citadel of Ricks', 'url': 'https://r...",https://rickandmortyapi.com/api/character/avat...,"[https://rickandmortyapi.com/api/episode/1, ht...",https://rickandmortyapi.com/api/character/2,2017-11-04T18:50:21.651Z
2,3,Summer Smith,Alive,Human,,Female,"{'name': 'Earth (Replacement Dimension)', 'url...","{'name': 'Earth (Replacement Dimension)', 'url...",https://rickandmortyapi.com/api/character/avat...,"[https://rickandmortyapi.com/api/episode/6, ht...",https://rickandmortyapi.com/api/character/3,2017-11-04T19:09:56.428Z
3,4,Beth Smith,Alive,Human,,Female,"{'name': 'Earth (Replacement Dimension)', 'url...","{'name': 'Earth (Replacement Dimension)', 'url...",https://rickandmortyapi.com/api/character/avat...,"[https://rickandmortyapi.com/api/episode/6, ht...",https://rickandmortyapi.com/api/character/4,2017-11-04T19:22:43.665Z
4,5,Jerry Smith,Alive,Human,,Male,"{'name': 'Earth (Replacement Dimension)', 'url...","{'name': 'Earth (Replacement Dimension)', 'url...",https://rickandmortyapi.com/api/character/avat...,"[https://rickandmortyapi.com/api/episode/6, ht...",https://rickandmortyapi.com/api/character/5,2017-11-04T19:26:56.301Z
...,...,...,...,...,...,...,...,...,...,...,...,...
821,822,Young Jerry,unknown,Human,,Male,"{'name': 'Earth (Unknown dimension)', 'url': '...","{'name': 'Earth (Unknown dimension)', 'url': '...",https://rickandmortyapi.com/api/character/avat...,[https://rickandmortyapi.com/api/episode/51],https://rickandmortyapi.com/api/character/822,2021-11-02T17:18:31.934Z
822,823,Young Beth,unknown,Human,,Female,"{'name': 'Earth (Unknown dimension)', 'url': '...","{'name': 'Earth (Unknown dimension)', 'url': '...",https://rickandmortyapi.com/api/character/avat...,[https://rickandmortyapi.com/api/episode/51],https://rickandmortyapi.com/api/character/823,2021-11-02T17:19:00.951Z
823,824,Young Beth,unknown,Human,,Female,"{'name': 'Earth (Unknown dimension)', 'url': '...","{'name': 'Earth (Unknown dimension)', 'url': '...",https://rickandmortyapi.com/api/character/avat...,[https://rickandmortyapi.com/api/episode/51],https://rickandmortyapi.com/api/character/824,2021-11-02T17:19:47.957Z
824,825,Young Jerry,unknown,Human,,Male,"{'name': 'Earth (Unknown dimension)', 'url': '...","{'name': 'Earth (Unknown dimension)', 'url': '...",https://rickandmortyapi.com/api/character/avat...,[https://rickandmortyapi.com/api/episode/51],https://rickandmortyapi.com/api/character/825,2021-11-02T17:20:14.305Z
825,826,Butter Robot,Alive,Robot,Passing Butter Robot,Genderless,"{'name': 'Earth (Replacement Dimension)', 'url...","{'name': 'Earth (Replacement Dimension)', 'url...",https://rickandmortyapi.com/api/character/avat...,[https://rickandmortyapi.com/api/episode/9],https://rickandmortyapi.com/api/character/826,2021-11-02T17:24:37.458Z

In [9]:
def prepare_characters(df_character):
    #Take ids from all episodies and make a column for the ids, 
    df_character["episode_ids"] = df_character["episode"].apply(
        lambda urls: [int(url.split("/")[-1]) for url in urls]
    )
    
    df_character["location_id"] = df_character["location"].apply(
        lambda loc: int(loc["url"].split("/")[-1]) if loc["url"] else None
    )
    
    df_character["location_id"] = df_character["location_id"].astype("Int64")
    
    # Delete the old episodies column
    df_character = df_character.drop("episode", axis=1)
    df_character = df_character.drop("image", axis=1)
    df_character = df_character.drop("url", axis=1)
    df_character = df_character.drop("location", axis=1)
    df_character = df_character.drop("origin", axis=1)
    df_character = df_character.drop("created",axis=1)
    
    return df_character

def prepare_locations(df_location):
    df_location = df_location.drop("residents", axis=1)
    df_location = df_location.drop("url", axis=1)
    df_location = df_location.drop("created", axis=1)
    return df_location

def prepare_episodes(df_episode):
    df_episode = df_episode.drop("characters", axis=1)
    df_episode = df_episode.drop("url", axis=1)
    df_episode = df_episode.drop("created", axis=1)
    return df_episode

In [10]:
df_episode = prepare_episodes(df_episode)
df_episode

,id,name,air_date,episode
0,1,Pilot,"December 2, 2013",S01E01
1,2,Lawnmower Dog,"December 9, 2013",S01E02
2,3,Anatomy Park,"December 16, 2013",S01E03
3,4,M. Night Shaym-Aliens!,"January 13, 2014",S01E04
4,5,Meeseeks and Destroy,"January 20, 2014",S01E05
5,6,Rick Potion #9,"January 27, 2014",S01E06
6,7,Raising Gazorpazorp,"March 10, 2014",S01E07
7,8,Rixty Minutes,"March 17, 2014",S01E08
8,9,Something Ricked This Way Comes,"March 24, 2014",S01E09
9,10,Close Rick-counters of the Rick Kind,"April 7, 2014",S01E10
10,11,Ricksy Business,"April 14, 2014",S01E11
11,12,A Rickle in Time,"July 26, 2015",S02E01
12,13,Mortynight Run,"August 2, 2015",S02E02
13,14,Auto Erotic Assimilation,"August 9, 2015",S02E03
14,15,Total Rickall,"August 16, 2015",S02E04
15,16,Get Schwifty,"August 23, 2015",S02E05
16,17,The Ricks Must Be Crazy,"August 30, 2015",S02E06
17,18,Big Trouble in Little Sanchez,"September 13, 2015",S02E07
18,19,Interdimensional Cable 2: Tempting Fate,"September 20, 2015",S02E08
19,20,Look Who's Purging Now,"September 27, 2015",S02E09
20,21,The Wedding Squanchers,"October 4, 2015",S02E10
21,22,The Rickshank Rickdemption,"April 1, 2017",S03E01
22,23,Rickmancing the Stone,"July 30, 2017",S03E02
23,24,Pickle Rick,"August 6, 2017",S03E03
24,25,Vindicators 3: The Return of Worldender,"August 13, 2017",S03E04
25,26,The Whirly Dirly Conspiracy,"August 20, 2017",S03E05
26,27,Rest and Ricklaxation,"August 27, 2017",S03E06
27,28,The Ricklantis Mixup,"September 10, 2017",S03E07
28,29,Morty's Mind Blowers,"September 17, 2017",S03E08
29,30,The ABC's of Beth,"September 24, 2017",S03E09
30,31,The Rickchurian Mortydate,"October 1, 2017",S03E10
31,32,"Edge of Tomorty: Rick, Die, Rickpeat","November 10, 2019",S04E01
32,33,The Old Man and the Seat,"November 17, 2019",S04E02
33,34,One Crew Over the Crewcoo's Morty,"November 24, 2019",S04E03
34,35,Claw and Hoarder: Special Ricktim's Morty,"December 8, 2019",S04E04
35,36,Rattlestar Ricklactica,"December 15, 2019",S04E05
36,37,Never Ricking Morty,"May 3, 2020",S04E06
37,38,Promortyus,"May 10, 2020",S04E07
38,39,The Vat of Acid Episode,"May 17, 2020",S04E08
39,40,Childrick of Mort,"May 24, 2020",S04E09
40,41,Star Mort: Rickturn of the Jerri,"May 31, 2020",S04E10
41,42,Mort Dinner Rick Andre,"June 20, 2021",S05E01
42,43,Mortyplicity,"June 27, 2021",S05E02
43,44,A Rickconvenient Mort,"July 4, 2021",S05E03
44,45,Rickdependence Spray,"July 11, 2021",S05E04
45,46,Amortycan Grickfitti,"July 18, 2021",S05E05
46,47,Rick & Morty's Thanksploitation Spectacular,"July 25, 2021",S05E06
47,48,Gotron Jerrysis Rickvangelion,"August 1, 2021",S05E07
48,49,Rickternal Friendshine of the Spotless Mort,"August 8, 2021",S05E08
49,50,Forgetting Sarick Mortshall,"September 5, 2021",S05E09
50,51,Rickmurai Jack,"September 5, 2021",S05E10

In [11]:
df_location = prepare_locations(df_location)

df_location

      id                       name           type              dimension
0      1              Earth (C-137)         Planet        Dimension C-137
1      2                   Abadango        Cluster                unknown
2      3           Citadel of Ricks  Space station                unknown
3      4          Worldender's lair         Planet                unknown
4      5               Anatomy Park     Microverse        Dimension C-137
..   ...                        ...            ...                    ...
121  122               Avian Planet         Planet  Replacement Dimension
122  123  Normal Size Bug Dimension      Dimension
123  124                 Slartivart         Planet  Replacement Dimension
124  125  Rick and Two Crows Planet         Planet  Replacement Dimension
125  126            Rick's Memories         Memory

[126 rows x 4 columns]

In [12]:
df_character = prepare_characters(df_character)
df_character

,id,name,status,species,type,gender,episode_ids,location_id
0,1,Rick Sanchez,Alive,Human,,Male,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",3
1,2,Morty Smith,Alive,Human,,Male,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",3
2,3,Summer Smith,Alive,Human,,Female,"[6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 1...",20
3,4,Beth Smith,Alive,Human,,Female,"[6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 18, 19, 2...",20
4,5,Jerry Smith,Alive,Human,,Male,"[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 1...",20
...,...,...,...,...,...,...,...,...
821,822,Young Jerry,unknown,Human,,Male,[51],30
822,823,Young Beth,unknown,Human,,Female,[51],30
823,824,Young Beth,unknown,Human,,Female,[51],30
824,825,Young Jerry,unknown,Human,,Male,[51],30
825,826,Butter Robot,Alive,Robot,Passing Butter Robot,Genderless,[9],20

In [13]:
def make_character_episode_table():
    character_episode = df_character[["id","episode_ids"]].explode("episode_ids")
    character_episode = character_episode.rename(columns={"id": "character_id", "episode_ids": "episode_id"})
    character_episode = character_episode.reset_index(drop=True)
    return character_episode

In [14]:
df_character_episode = make_character_episode_table()
df_character_episode

      character_id episode_id
0                1          1
1                1          2
2                1          3
3                1          4
4                1          5
...            ...        ...
1262           822         51
1263           823         51
1264           824         51
1265           825         51
1266           826          9

[1267 rows x 2 columns]

In [15]:
#Limpiamos las las columnas de df_characters que ahora estan en la tabla relacional de df_characters_episodes
df_character = df_character.drop("episode_ids", axis=1)

df_character

,id,name,status,species,type,gender,location_id
0,1,Rick Sanchez,Alive,Human,,Male,3
1,2,Morty Smith,Alive,Human,,Male,3
2,3,Summer Smith,Alive,Human,,Female,20
3,4,Beth Smith,Alive,Human,,Female,20
4,5,Jerry Smith,Alive,Human,,Male,20
...,...,...,...,...,...,...,...
821,822,Young Jerry,unknown,Human,,Male,30
822,823,Young Beth,unknown,Human,,Female,30
823,824,Young Beth,unknown,Human,,Female,30
824,825,Young Jerry,unknown,Human,,Male,30
825,826,Butter Robot,Alive,Robot,Passing Butter Robot,Genderless,20

In [19]:
DATA_BASE_URL = "postgresql://postgres:xcbAlPujxcvXLamqinvxUbJDlixgRXoS@switchback.proxy.rlwy.net:44026/railway"

engine = create_engine(DATA_BASE_URL)

In [20]:
metadata = MetaData()

locations = Table("locations", metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String),
    Column("type", String),
    Column("dimension", String),
)

characters = Table("characters", metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String),
    Column("status", String),
    Column("species", String),
    Column("type", String),
    Column("gender", String),
    Column("location_id", Integer, ForeignKey("locations.id")),  # ← relación
)

episodes = Table("episodes", metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String),
    Column("air_date", String),
    Column("episode", String),
)

character_episode = Table("character_episode", metadata,
    Column("character_id", Integer, ForeignKey("characters.id")),  # ← relación
    Column("episode_id", Integer, ForeignKey("episodes.id")),      # ← relación
)

metadata.create_all(engine)  # crea todo de golpe con las relaciones ya definidas

In [21]:
# 2. Insertar datos (orden importante por las FKs)
df_location.to_sql("locations", engine, if_exists="append", index=False)
df_episode.to_sql("episodes", engine, if_exists="append", index=False)
df_character.to_sql("characters", engine, if_exists="append", index=False)
df_character_episode.to_sql("character_episode", engine, if_exists="append", index=False)

267